config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "workouts#index"
  resources :workouts

  get "/calendar", to: "workouts#calendar"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :results
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :participant
  belongs_to :workout

  def formatted_result
    return nil unless result

    seconds = result % 60
    minutes = (result / 60) % 60

    format("%02d:%02d", minutes, seconds)
  end
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :exercise
  belongs_to :workout
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :rounds
  has_many :results

  enum :variety, [ :amrap, :for_time, :tabata, :emom ]

  FORMATTED_VARIETY = {
    "amrap" => "AMRAP",
    "for_time" => "Time",
    "tabata" => "Tabata",
    "emom" => "EMOM"
  }

  def start_time
    date
  end

  def strength
    rounds.find_by(number: 0)
  end

  def non_strength_rounds
    rounds.where.not(number: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # before_action :require_authentication, only: %i[new create edit update]

  def index
    @workouts = Workout.order(date: :desc).paginate(page: params[:page], per_page: 5)
  end

  def show
    @workout = Workout.find(params[:id])
    @rounds = @workout.rounds
    @strength = @workout.strength
  end

  def calendar
    start_date = if params[:start_date]
      params[:start_date].to_date.beginning_of_month
    else
      Date.today.beginning_of_month
    end
    @workouts = Workout.where(date: start_date..start_date.end_of_month)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="border-gray-200 bg-navbar-black drop-shadow-2xl">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-center mx-auto p-4">
    <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
        <%= image_tag("logo.webp", class: "h-16") %>
    </a>
    <span class="self-center text-2xl font-semibold whitespace-nowrap text-text-blue ml-4">Bagus Stats</span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-bg-blue m-0 h-screen background">
  <head>
    <title><%= content_for(:title) || "Bagus Stats" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-14 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/workouts/_workout.html.erb
<div class="w-3/4 mx-auto my-6 bg-card-blue rounded-xl shadow-md overflow-hidden md:max-w-2xl">
    <div class="md:flex md:divide-x divide-y md:divide-y-0 divide-dotted divide-text-blue">
        <div class="p-6">
            <a href="#" class="block mt-1 text-base leading-tight font-medium text-text-blue hover:underline">
              <%= workout.date.strftime('%d/%m/%Y') %> - (<%= workout.date.strftime('%a') %>)
            </a>
            <div class="uppercase tracking-wide text-sm text-text-blue  font-semibold"><%= Workout::FORMATTED_VARIETY[workout.variety] %></div>
            <p class="mt-2 text-slate-500"><%= workout.time_cap %> Mins
            </p>
        </div>
        <% workout.rounds.each do |round| %>
            <div class="p-6 text-center space-x-4"> <div class="underline text-text-dark-blue"><%= round.number.zero? ? "Strength" : "Round: #{round.number}"%></div>
              <div class="text-sm my-1 text-text-blue"> <%= round.exercise.name %> </div>
              <% if round.reps.present? %>
                <div class="text-sm text-text-blue"> <%= round.reps %> Reps</div>
              <% end %>
              <% if round.notes.present? %>
                <div class="text-sm text-text-blue"> <%= round.notes %> </div>
              <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/workouts/calendar.html.erb
<%= month_calendar(partial: 'calendars/calendar', events: @workouts) do |date, workouts| %>
  <div class="<%= "#{workouts.empty? ? '' : 'lg:ml-6 lg:mt-6'}"%>">
    <div class="underline underline-offset-4">
      <%= date.day %>.
    </div>
    <% unless workouts.empty? %>
      <% workouts.each do |workout|  %>
        <%= link_to workout, class: "bg-cyan-700 inline-flex items-center justify-center p-0.5 overflow-hidden text-xs font-medium rounded-lg group mt-2" do %>
          <span class="text-white px-2 py-2 rounded transition-all ease-in duration-75 shadow-xl">
            <%= Workout::FORMATTED_VARIETY[workout.variety] %>
          </span>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/workouts/index.html.erb
<%= turbo_frame_tag "workouts", src: workouts_path(format: :turbo_stream), loading: :lazy %>
<% if @search.blank? && @workouts.next_page %>
    <%= turbo_frame_tag "load_more", src: workouts_path(page: @workouts.next_page, format: :turbo_stream), loading: :lazy %>
<% end %>

app/views/workouts/index.turbo_stream.erb
<%= turbo_stream.append "workouts" do %>
  <%= render partial: "workouts/workout", collection: @workouts %>
<% end %>

<% if @workouts.next_page %>
  <%= turbo_stream.replace "load_more" do %>
    <%= turbo_frame_tag "load_more", src: workouts_path(page: @workouts.next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

<%= turbo_stream.update "current_page", @workouts.current_page %>